portfolio/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :landing, :only =>'index'
  resources :users, :only => [:show, :index]
  resources :users do
    resources :post
  end
  root "landing#index"
end

portfolio/app/controllers/users_controllers.rb
class UsersController < ApplicationController
  def index
  end

  def show
    @projects = Project.get_all
  end
end

portfolio/app/views/landing/index.html.erb
<div class="well">
<h1>Hello! Welcome!</h1>

<p>You have arrived at the personal webiste of Marty Kovach, web devloper and aspiring dreamer! If you were looking for me, you found me! This place is a bit of a mess at the moment, got some exciting features I am hoping to add here eventually..
</p>
<p>Feel free to click on through and take a look! or not, it's your choice. </p>
<br><br>

<p>Once again... </p>


<h1>Welcome!</h1>
</div>

portfolio/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Marty's Site</title>
    <%= csrf_meta_tags %>
      <%= stylesheet_link_tag 'landing', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <div id="use_nav" class="navbar navbar-default">
      <div class="container-fluid">
        <div class="nabar-header">
        <%= link_to "The Portfolio", '/', :class => "navbar-brand" %>
        <% if user_signed_in? %>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">

            <li><%= link_to "Logged in as #{current_user.user_name}", edit_user_registration_path %></li>
            <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
            <% else %>

          </ul>
          <ul class="nav navbar-nav">
            <li><%= link_to "Sign up", new_user_registration_path %></li>
            <li><%= link_to "Log in", new_user_session_path %></li>
          </ul>
            <% end %>
          <ul class="nav navbar-nav">
            <li><%= link_to "About Me", users_path %></li>
            <li><%= link_to "Projects", user_path(User.find(1))%></li>

          </ul>

          </div>
        </div>
      </div>
    </div>
  </head>

  <body  >
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

portfolio/app/views/users/show.html.erb
<div class="well">
<h1><strong>Projects</strong></h1>

<p> Like an adventurer collecting an impressive amount of treasure on thier journies, I too have amassed a fair amount of <strong>treasures.</strong> By treausres I mean <strong>GitHub Repositories</strong>. Most of them are projects that were created during my time at Epicodus. Some of them are polished looking websites and web apps with functionality, others remanant's from the learning process. </p>
<br>
<p> The following repos are...</p>
</div>
<div class="well">
  <h2>The Best of my Best:</h2>
  <h5>note: the titles of the projects are prefixed with the main langauge/framework the project was made in.</h5>
</div>
<% if @projects.any? %>
  <% @projects.each do |project| %>
    <% if project['stargazers_count'] > 0 %>
  <div class="well">
    <h4>Title: <%= project['name'] %> </h4>

   <br>
   <h4>Description:</h4>
   <%= project['description'] %>
   <hr>
   <h4>This project has gotten this many stars! <%= project['stargazers_count'] %></h4>
 </div>
 <% end %>
 <% end %>
<% else %>
 <h1>Something has gone horrifically wrong if you are seeing this...</h1>
 <% end %>