config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :landing, :only =>'index'
  resources :users, :only => [:show, :index]
  resources :users do
    resources :posts, :only =>[:new, :create, :edit, :update, :destroy]
  end
  resources :posts, :only => [:index, :show]
  resources :projects, :only => 'index'
  root "landing#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
   has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :user_name, :is_admin])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :user_name, :is_admin])
  end
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = current_user
    @posts = Post.all
  end
  def  show
    @post = Post.find(params[:id])
  end
  def new
    @user = current_user
      if @user.is_admin === true
      @post = @user.posts.new
    else
      flash[:alert] = "Admins only"
      redirect_to posts_path
    end
  end
  def create
    @user = current_user
    @post = @user.posts.new(post_params)
    if @post.save
        flash[:notice] = "You have added new blog post!"
        redirect_to posts_path
      else
        flash[:alert] = "Woops"
        render :new
      end
    end
    def edit
      @user = current_user
      @post = Post.find(params[:id])
    end
    def update
      @user = current_user
      @post = Post.find(params[:id])
        if @post.update(post_params)
          flash[:notice]= "You have edited this blog post"
          redirect_to posts_path
        else
          render edit
        end
    end
    def destroy
      @user = current_user
      @post = Post.find(params[:id])
    if @post.destroy
      flash[:notice]="You have removed this blog post"
      redirect_to posts_path
      end
    end

    private
    def post_params
      params.require(:post).permit(:title, :content)
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
      @projects = Project.get_all
  end
end

app/controllers/users_controllers.rb
class UsersController < ApplicationController
  def index
  end

  def show
  
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/landing/index.html.erb
<div class="well">
  <% if current_page?('/')%>
<h1>Hello! Welcome!</h1>

<p>You have arrived at the personal webiste of Marty Kovach, web devloper and aspiring dreamer! If you were looking for me, you found me! This place is a bit of a mess at the moment, got some exciting features I am hoping to add here eventually..
</p>
<p>Feel free to click on through and take a look! or not, it's your choice. </p>
<br><br>

<p>Once again... </p>


<h1>Welcome!</h1>
<% else%>
<h1> Just who am I?</h1>

<h3>A Background Most Brief</h3>
<p>Before I began my journey to become a web developer, I worked at my local Fred Meyer. I gained valuable experiences in honing my professional skills in customer service, teamwork, spill response, but by the end I was trapped in soul-curshing cycle of work-eat-sleep. I was ready to pursure something that I was passonaite, something that I could see myself doing for a long time. That something was programming.  I had always toyed around with the idea of programming but never took it too seriously, as it seemed like a bunch of black magic I could not even begin to understand.  After close to a full year and half of an arduous retail existence, I was ready to try coding.</p>

<p>I enrolled into the Epicodus part-time Introduction to Programming class, to get a feel if becoming a web developer was something I wanted to do.  I was only three weeks into that program, and I knew that I was ready to take the deep dive.  Months have past since that pivotal moment, and the black magic that was coding, has been de-mystified.  Along with my new understanding of programming, I have confidence in my skills using html, css, javascript, and ruby, and  as well as my abilities to use jquery and bootstrap to make more a dynamic website, than an unchanging electric brick wall.
</p>
</div>
<div class="well">
 <h3> Where else to find me! </h3>
 <a href="https://www.linkedin.com/in/marty-kovach-tye105">LinkedIn!</a>
 <br>
 <a href="https://github.com/tyedye105">GitHub!</a>
</div>
<% end %>
</div>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
<div class="well">
  <h3>Oops there were some errors. Please try again:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Marty's Site</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <div id="use_nav" class="navbar navbar-default">
      <div class="container-fluid">
        <div class="nabar-header">
        <%= link_to "The Portfolio", '/', :class => "navbar-brand" %>
        <% if user_signed_in? %>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">

            <li><%= link_to "Logged in as #{current_user.user_name}", edit_user_registration_path %></li>
            <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
            <% else %>

          </ul>
          <ul class="nav navbar-nav">
            <li><%= link_to "Sign up", new_user_registration_path %></li>
            <li><%= link_to "Log in", new_user_session_path %></li>
          </ul>
            <% end %>
          <ul class="nav navbar-nav">
            <li><%= link_to "About Me", landing_index_path %></li>
            <li><%= link_to "Projects", projects_path %></li>
            <li><%= link_to "Blog Posts", posts_path %></li>
          </ul>

          </div>
          <h4><%= flash[:alert] %></h4>
         <br>
         <h4><%= flash[:notice] %></h4>
        </div>
      </div>
    </div>
  </head>

  <body  >

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/edit.html.erb
<div class="well">
  <%= render "/layouts/errors", :object => @post %>
<h1>Add a new blog post!</h1>
<%= form_for [@user, @post] do |f| %>
  <div class="form-group">
    <%=f.label :title  %>
    <%=f.text_field :title  %>
  </div>
  <div class="form-group">
    <%=f.label :content  %>
    <br>
    <%=f.text_area :content  %>
  </div>
  <%= f.hidden_field :user_id, :value => @user.id %>
  <%= f.submit  %>
</div>
<% end %>
</div>

app/views/posts/index.html.erb
<div class="well">
<h1>What Marty's Been Up To Recently</h1>
<% if @user.is_admin?  %>
<%= button_to "Add New Blog Post", new_user_post_path(@user), method: :get%>
<% end %>
<%if @posts.any? %>
  <% @posts.each do |post| %>
  <h2><%= link_to post.title, post_path(post.id) %></h2>
  <% if @user.is_admin %>
    <%= link_to "Edit", edit_user_post_path(@user, post), :class => "btn btn-default" %>
    <%= link_to "Delete", user_post_path(@user, post),:class => "btn btn-default", :data => {:confirm => "Are you sure?",
                                           :method => "delete"}  %>
   <% end                                   %>
  <% end %>
  <% else %>
  <h2>There are currently no blog posts</h2>
  <% end %>
  </div>

app/views/posts/new.html.erb
<div class="well">
  <%= render "/layouts/errors", :object => @post %>
<h1>Add a new blog post!</h1>
<%= form_for [@user, @post] do |f| %>
  <div class="form-group">
    <%=f.label :title  %>
    <%=f.text_field :title  %>
  </div>
  <div class="form-group">
    <%=f.label :content  %>
    <br>
    <%=f.text_area :content  %>
  </div>
  <%= f.hidden_field :user_id, :value => @user.id %>
  <%= f.submit  %>
</div>
<% end %>
</div>

app/views/posts/show.html.erb
<div class="well">
<h1 class="title"> <%= @post.title %> </h1>
<p> <%= @post.content %> </p>
</div>

app/views/projects/index.html.erb
<div class="well">
<h1><strong>Projects</strong></h1>

<p> Like an adventurer collecting an impressive amount of treasure on thier journies, I too have amassed a fair amount of <strong>treasures.</strong> By treausres I mean <strong>GitHub Repositories</strong>. Most of them are projects that were created during my time at Epicodus. Some of them are polished looking websites and web apps with functionality, others remanant's from the learning process. </p>
<br>
<p> The following repos are...</p>
</div>
<div class="well">
  <h2>The Best of my Best:</h2>
  <h5>note: the titles of the projects are prefixed with the main langauge/framework the project was made in.</h5>
</div>
<% if @projects.any? %>
  <% @projects.each do |project| %>
    <% if project['stargazers_count'] > 0 %>
  <div class="well">
    <h4>Title: <%= project['name'] %> </h4>

   <br>
   <h4>Description:</h4>
   <%= project['description'] %>
   <hr>
   <h4>This project has gotten this many stars! <%= project['stargazers_count'] %></h4>
 </div>
 <% end %>
 <% end %>
<% else %>
 <h1>Something has gone horrifically wrong if you are seeing this...</h1>
 <% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>